 <cfscript>
	Abs()
	ACos()
	AddSOAPRequestHeader()
	AddSOAPResponseHeader()
	ArrayAppend()
	ArrayAvg()
	ArrayClear()
	ArrayDeleteAt()
	ArrayInsertAt()
	ArrayIsEmpty()
	ArrayLen()
	ArrayMax()
	ArrayMin()
	ArrayNew()
	ArrayPrepend()
	ArrayResize()
	ArraySet()
	ArraySort()
	ArraySum()
	ArraySwap()
	ArrayToList()
	Asc()
	ASin()
	Atn()
	BinaryDecode()
	BinaryEncode()
	BitAnd()
	BitMaskClear()
	BitMaskRead()
	BitMaskSet()
	BitNot()
	BitOr()
	BitSHLN()
	BitSHRN()
	BitXor()
	Ceiling()
	CharsetDecode()
	CharsetEncode()
	Chr()
	CJustify()
	Compare()
	CompareNoCase()
	Cos()
	CreateDate()
	CreateDateTime()
	CreateObject()
	CreateODBCDate()
	CreateODBCDateTime()
	CreateODBCTime()
	CreateTime()
	CreateTimeSpan()
	CreateUUID()
	DateAdd()
	DateCompare()
	DateConvert()
	DateDiff()
	DateFormat()
	DatePart()
	Day()
	DayOfWeek()
	DayOfWeekAsString()
	DayOfYear()
	DaysInMonth()
	DaysInYear()
	DE()
	DecimalFormat()
	DecrementValue()
	Decrypt()
	DecryptBinary()
	DeleteClientVariable()
	DirectoryExists()
	DollarFormat()
	Duplicate()
	Encrypt()
	EncryptBinary()
	Evaluate()
	Exp()
	ExpandPath()
	FileExists()
	Find()
	FindNoCase()
	FindOneOf()
	FirstDayOfMonth()
	Fix()
	FormatBaseN()
	GetAuthUser()
	GetBaseTagData()
	GetBaseTagList()
	GetBaseTemplatePath()
	GetClientVariablesList()
	GetCurrentTemplatePath()
	GetDirectoryFromPath()
	GetEncoding()
	GetException()
	GetFileFromPath()
	GetFunctionList()
	GetGatewayHelper()
	GetHttpRequestData()
	GetHttpTimeString()
	GetLocale()
	GetLocaleDisplayName()
	GetLocalHostIP()
	GetMetaData()
	GetMetricData()
	GetPageContext()
	GetProfileSections()
	GetProfileString()
	GetSOAPRequest()
	GetSOAPRequestHeader()
	GetSOAPResponse()
	GetSOAPResponseHeader()
	GetTempDirectory()
	GetTempFile()
	GetTickCount()
	GetTimeZoneInfo()
	GetToken()
	Hash()
	Hour()
	HTMLCodeFormat()
	HTMLEditFormat()
	IIf()
	IncrementValue()
	InputBaseN()
	Insert()
	Int()
	IsArray()
	IsBinary()
	IsBoolean()
	IsCustomFunction()
	IsDate()
	IsDebugMode()
	IsDefined()
	IsLeapYear()
	IsLocalHost()
	IsNumeric()
	IsNumericDate()
	IsObject()
	IsQuery()
	IsSimpleValue()
	IsSOAPRequest()
	IsStruct()
	IsUserInRole()
	IsValid()
	IsWDDX()
	IsXML()
	IsXmlAttribute()
	IsXmlDoc()
	IsXmlElem()
	IsXmlNode()
	IsXmlRoot()
	JavaCast()
	JSStringFormat()
	LCase()
	Left()
	Len()
	ListAppend()
	ListChangeDelims()
	ListContains()
	ListContainsNoCase()
	ListDeleteAt()
	ListFind()
	ListFindNoCase()
	ListFirst()
	ListGetAt()
	ListInsertAt()
	ListLast()
	ListLen()
	ListPrepend()
	ListQualify()
	ListRest()
	ListSetAt()
	ListSort()
	ListToArray()
	ListValueCount()
	ListValueCountNoCase()
	LJustify()
	Log()
	Log10()
	LSCurrencyFormat()
	LSDateFormat()
	LSEuroCurrencyFormat()
	LSIsCurrency()
	LSIsDate()
	LSIsNumeric()
	LSNumberFormat()
	LSParseCurrency()
	LSParseDateTime()
	LSParseEuroCurrency()
	LSParseNumber()
	LSTimeFormat()
	LTrim()
	Max()
	Mid()
	Min()
	Minute()
	Month()
	MonthAsString()
	Now()
	NumberFormat()
	ParagraphFormat()
	ParseDateTime()
	Pi()
	PreserveSingleQuotes()
	Quarter()
	QueryAddColumn()
	QueryAddRow()
	QueryNew()
	QuerySetCell()
	QuotedValueList()
	Rand()
	Randomize()
	RandRange()
	REFind()
	REFindNoCase()
	ReleaseComObject()
	RemoveChars()
	RepeatString()
	Replace()
	ReplaceList()
	ReplaceNoCase()
	REReplace()
	REReplaceNoCase()
	Reverse()
	Right()
	RJustify()
	Round()
	RTrim()
	Second()
	SendGatewayMessage()
	SetEncoding()
	SetLocale()
	SetProfileString()
	SetVariable()
	Sgn()
	Sin()
	SpanExcluding()
	SpanIncluding()
	Sqr()
	StripCR()
	StructAppend()
	StructClear()
	StructCopy()
	StructCount()
	StructDelete()
	StructFind()
	StructFindKey()
	StructFindValue()
	StructGet()
	StructInsert()
	StructIsEmpty()
	StructKeyArray()
	StructKeyExists()
	StructKeyList()
	StructNew()
	StructSort()
	StructUpdate()
	Tan()
	TimeFormat()
	ToBase64()
	ToBinary()
	ToScript()
	ToString()
	Trim()
	UCase()
	URLDecode()
	URLEncodedFormat()
	URLSessionFormat()
	Val()
	ValueList()
	Week()
	Wrap()
	WriteOutput()
	XmlChildPos()
	XmlElemNew()
	XmlFormat()
	XmlGetNodeType()
	XmlNew()
	XmlParse()
	XmlSearch()
	XmlTransform()
	XmlValidate()
	Year()
	YesNoFormat()
 </cfscript>
<div>
	<cfabort>
	<cfapplet>
	<cfapplication>
	<cfargument>
	<cfassociate>
	<cfbreak>
	<cfcache>
	<cfcalendar>
	<cfcase></cfcase>
	<cfcatch></cfcatch>
	<cfchart></cfchart>
	<cfchartdata>
	<cfchartseries>
	<cfcol>
	<cfcollection>
	<cfcomponent>test</cfcomponent>
	<cfcontent>
	<cfcookie>
	<cfdefaultcase></cfdefaultcase>
	<cfdirectory>
	<cfdocument>
	<cfdocumentitem>
	<cfdocumentsection>
	<cfdump>
	<cfelse>
	<cfelseif>
	<cferror>
	<cfexecute>
	<cfexit>
	<cffile>
	<cfflush>
	<cfform>
	<cfformgroup>
	<cfformitem>
	<cfftp>
	<cffunction></cffunction>
	<cfgrid>
	<cfgridcolumn>
	<cfgridrow>
	<cfgridupdate>
	<cfheader>
	<cfhtmlhead>
	<cfhttp>
	<cfhttpparam>
	<cfif></cfif>
	<cfimport>
	<cfinclude>
	<cfindex>
	<cfinput>
	<cfinsert>
	<cfinvoke>
	<cfinvokeargument>
	<cfldap>
	<cflocation>
	<cflock>
	<cflog>
	<cflogin>
	<cfloginuser>
	<cflogout>
	<cfloop></cfloop>
	<cfmail>
	<cfmailparam>
	<cfmailpart>
	<cfmodule>
	<cfNTauthenticate>
	<cfobject>
	<cfobjectcache>
	<cfoutput query="#Session.dsn#">
		
	</cfoutput>
	<cfparam>
	<cfpop>
	<cfprocessingdirective>
	<cfprocparam>
	<cfprocresult>
	<cfproperty>
	<cfquery dbtype="">
		select blah from 
	</cfquery>
	<cfqueryparam>
	<cfregistry>
	<cfreport>
	<cfreportparam>
	<cfrethrow>
	<cfreturn>
	<cfsavecontent>
	<cfschedule>
	<cfscript>
		arrayNew()
		function blah() {
			d = "#test#";
		}
	</cfscript>
	<cfsearch>
	<cfselect>
	<cfset>
	<cfsetting>
	<cfsilent>
	<cfslider>
	<cfstoredproc>
	<cfswitch></cfswitch>
	<cftable>
	<cftextarea>
	<cfthrow>
	<cftimer>
	<cftrace>
	<cftransaction>
	<cftree>
	<cftreeitem>
	<cftry>
	<cfupdate>
	<cfwddx>
	<cfxml>
</div>