<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>foldingStartMarker</key>
	<string>(^.*{[^}]*$|^.*\([^\)]*$|^.*/\*(?!.*\*/).*$)</string>
	<key>foldingStopMarker</key>
	<string>(^\s*\}|^\s*\)|^(?!.*/\*).*\*/)</string>
	<key>name</key>
	<string>CFML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cfml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.cfml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(function)\s+([a-zA-Z_$]\w*)?\s*\((.*?)\)</string>
			<key>name</key>
			<string>meta.function.cfml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.cfml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.cfml</string>
			<key>swallow</key>
			<string>\\.</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|while|for|return|else)\b</string>
			<key>name</key>
			<string>keyword.control.cfml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=|\+|\-|\*|\/|\^|\&amp;|\b(?i:mod|not|and|or|xor|eqv|imp|is|eq|neq|gt|ge|gte|lt|le|lte|contains|does not contain)\b</string>
			<key>name</key>
			<string>keyword.operator.cfml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!cfdump\s)\b(var)\b</string>
			<key>name</key>
			<string>storage.type.var</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|null|true)\b</string>
			<key>name</key>
			<string>constant.language.cfml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?))\b</string>
			<key>name</key>
			<string>constant.numeric.cfml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\.)(?i:CurrentRow|RecordCount|ColumnList)\b</string>
			<key>name</key>
			<string>support.constant.cfml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:Form|Session|Application|Server|Client|Request|CGI|URL|Variables|Arguments)\b</string>
			<key>name</key>
			<string>variable.language.cfml.scope</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cfmx-functions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>cfmx-functions</key>
		<dict>
			<key>match</key>
			<string>(?x)
\b(?i:
 Array((Ap|Pre)pend|Avg|Clear|(Delete|Insert)At|IsEmpty|Len|Max|Min|New|Resize|Set|Sort|Sum|Swap|ToList)
|List((Ap|Pre)pend|ChangeDelims|(Contains|Find|ValueCount)(NoCase)?|(Delete|Get|Insert|Set)At
|First|Last|Len|Qualify|Rest|Sort|ToArray)|A(sc|tn)|(Binary|Charset)(De|En)code|Bit(And|Mask(Clear|Read
|Set)|Not|Or|SHLN|SHRN|Xor)|Abs|A?(Sin|Cos)|AddSOAPRe(quest|sponse)Header|Ceiling|Chr|Compare(NoCase)?
|Create(Object|UUID|((ODBC)?(Date(Time)?|Time))|TimeSpan)|Date(Add|Co(mpare|nvert)|Diff|Format|Part)
|Day((sIn|Of)(Week(AsString)?|Year|Month))?|FirstDayOfMonth|De(cimalFormat|leteClientVariable)?
|(De|In)crementValue|(De|En)crypt(Binary)?|(R|L|C)?(Trim|Justify)|(Directory|File)Exists|Fix|(Format
|Input)BaseN|(RE)?(Find|Replace)(NoCase|OneOf|List)?|(Duplic|Evalu)ate|Exp(andPath)?|Get(AuthUser
|Encoding|Exception|GatewayHelper|PageContext|TickCount|TimeZoneInfo|Token|Base(Tag(Data|List))
|(ClientVariables|Function)List|(Base|Current|(Directory|File)From)(Template)?Path|Http(RequestData
|TimeString)|Local(e(DisplayName)?|HostIP)|Met(ric|a)Data|Profile(Sections|String)|Temp(Directory|File)
|SOAPRe(sponse|quest)(Header)?)|Hash|Hour|IIf|In(ser)?t|HTML(Code|Edit)Format|Is(Array|Binary|Boolean
|CustomFunction|Date|DebugMode|Defined|LeapYear|LocalHost|Numeric(Date)?|Object|Query|SimpleValue
|SOAPRequest|Struct|UserInRole|Valid|WDDX|XML(Attribute|Doc|Elem|Node|Root)?)|JavaCast|(L|U)Case|Left
|Len|Log(10)?|LS(((Euro)?Currency|Date|Number|Time)Format|Is(Currency|Date|Numeric)|Parse((Euro)?
Currency|DateTime|Number))|Max|Mi(d|n|nute)|Month(AsString)?|Now|Right|Round|Second|SendGatewayMessage
|ParseDateTime|Pi|(Dollar|JSString|Number|Paragraph|Time|YesNo)Format|PreserveSingleQuotes|Rand(omize
|Range)?|Qu(arter|(ery(Add(Column|Row)|New|SetCell))|otedValueList)|Span(Ex|In)cluding|Sqr|StripCR|Sgn
|Re(leaseComObject|moveChars|peatString|verse)|Set(Encoding|Locale|ProfileString|Variable)
|Struct(Append|Clear|Co(py|unt)|Delete|Find(Key|Value)?|Get|Insert|IsEmpty|Key(Array|Exists|List)|New
|Sort|Update)|Tan|To(Base64|Binary|Script|String)|URL(Decode|(Encoded|Session)(Format)?)|Val(ueList)?
|Week|Wrap|WriteOutput|Year|Xml(ChildPos|ElemNew|Format|GetNodeType|New|Parse|Search|Transform|Validate)
)\b</string>
			<key>name</key>
			<string>support.function.cfml</string>
		</dict>
		<key>interpolated-cfmx</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#(?=.*?#)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.cfml</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.cfml.embedded.line.html</string>
					<key>end</key>
					<string>#</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cfml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated-cfmx</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.cfml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated-cfmx</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.cfml</string>
	<key>uuid</key>
	<string>93D17B74-60FA-4070-86C8-CE0F6141130F</string>
</dict>
</plist>
