<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>ColdFusion 8</string>
	<key>fileTypes</key>
	<array>
		<string>cfm</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:
		  head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl|colgroup
		 |cf(if|loop|output|query|function|script|switch|case|defaultcase|component|silent|try|catch)
		  )\b.*?&gt;
		|&lt;!---(?!.*---&gt;)
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:
		  head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl|colgroup
		 |cf(if|loop|output|query|function|script|switch|case|defaultcase|component|silent|try|catch)
		  )&gt;
		|^(?!.*?&lt;!---).*?---&gt;$
		)</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>HTML (CFML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#cfcomment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:cfquery))\b(?![^&gt;]*/&gt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cfml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&lt;/)((?i:cfquery))(&gt;)(?:\s*\n)?</string>
			<key>name</key>
			<string>source.sql.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cfml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.cfml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=&lt;/(?i:cfquery))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.other.table-name.sql</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.other.field-name.sql</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\w+?)\.(\w+)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cfcomment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#embedded-code</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#cf-tag</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string-single-quoted</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?:^\s+)?(&lt;)((?i:cfscript))\b(?![^&gt;]*/&gt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;=&lt;/(cfscript|CFSCRIPT))(&gt;)(?:\s*\n)?</string>
			<key>endCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.cfml</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.cfml.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.cfml</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!&lt;/(?:cfscript|CFSCRIPT))(&gt;)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tag.cfml</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.cfml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(&lt;/)((?i:cfscript))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.cfml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(//).*?((?=&lt;/cfscript)|$\n?)</string>
							<key>name</key>
							<string>comment.line.double-slash.cfml</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>/\*</string>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.cfml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\*/$|(?=&lt;/cfscript)</string>
							<key>name</key>
							<string>comment.block.cfml</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.cfml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded-code</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cffunction</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#cf-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#custom-tag</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>cf-tag</key>
		<dict>
			<key>begin</key>
			<string>(?x)(&lt;/?)(cf(
                     a(bort|pp(let|lication)|rgument|ssociate)|break
                    |c(a(che|lendar|se|tch)|hart(data|series)?|o(l|llection|mponent|ntent|okie))
                    |d(efaultcase|irectory|ocument(item|section)?|ump)|e(lse(if)?|rror|xecute|xit)
                    |f(ile|lush|orm(group|item)?|tp|unction)|g(rid(column|row|update)?)
                    |h(eader|tmlhead|ttp(param)?)|i(f|mport|n(clude|dex|put|sert|voke(argument)?))
                    |l(dap|o(cation|ck|g(out)?|gin(user)?|op))|m(ail(param|part)?|odule)|NTauthenticate
                    |o(bject(cache)?|utput)|p(aram|op|r(ocessingdirective|oc(param|result)|operty))
                    |query(param)?|r(e(throw|turn|gistry|port(param)?))
                    |s(avecontent|c(hedule|ript)|e(arch|(lec)?t(ting)?)|ilent|lider|toredproc|witch)
                    |t(able|extarea|hrow|imer|r(ace|ansaction|ee(item)?|y))|update|wddx|xml
				))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.cfml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(/?&gt;)</string>
			<key>name</key>
			<string>meta.tag.language.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.cfml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>cfcomment</key>
		<dict>
			<key>begin</key>
			<string>&lt;!---</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>---&gt;</string>
			<key>name</key>
			<string>comment.block.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#cfcomment</string>
				</dict>
			</array>
		</dict>
		<key>cffunction</key>
		<dict>
			<key>begin</key>
			<string>&lt;(cffunction)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.cfml</string>
				</dict>
			</dict>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.tag.language.cfml.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.cfml</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function-name.cfml</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=name=)(")([A-Za-z$_0-9]+)(")</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.cfml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>custom-tag</key>
		<dict>
			<key>begin</key>
			<string>&lt;cf_</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>meta.tag.language.cfml.custom</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=cf_)([^\s]+)</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.cfml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<key>embedded-code</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.cfml.embedded.line.empty.whitespace.html</string>
						</dict>
					</dict>
					<key>match</key>
					<string>#(\s*)#</string>
					<key>name</key>
					<string>source.cfml.embedded.line.empty.html</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.variable.cfml</string>
						</dict>
					</dict>
					<key>end</key>
					<string>#</string>
					<key>name</key>
					<string>source.cfml.embedded.line.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.cfml</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.cfml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#embedded-code</string>
				</dict>
			</array>
		</dict>
		<key>tag-attribute</key>
		<dict>
			<key>match</key>
			<string>\b([a-zA-Z_]+)</string>
			<key>name</key>
			<string>entity.other.attribute-name.cfml</string>
		</dict>
		<key>tag-stuff</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-attribute</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.cfml</string>
	<key>uuid</key>
	<string>6EE1160A-C5B8-4C16-9B21-00A6E0A88EDE</string>
</dict>
</plist>
